# Generated by Django 5.0.3 on 2024-04-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0002_commentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='suj',
            new_name='subject',
        ),
    ]
