# Generated by Django 5.0.3 on 2024-04-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0003_rename_suj_commentmodel_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentModel',
            new_name='ContactModel',
        ),
    ]
