# Generated by Django 5.0.3 on 2024-04-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0006_remove_blogpost_category_blogpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipe_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='recipe_slider_img')),
            ],
        ),
    ]
