# Generated by Django 5.0.3 on 2024-04-17 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0007_recipe_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipe_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('prepaired_time', models.PositiveIntegerField()),
                ('coock_time', models.PositiveIntegerField()),
                ('Servings_person', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('Ingredients', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe_slider',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='delicious.recipe_blog'),
            preserve_default=False,
        ),
    ]
