# Generated by Django 5.0.3 on 2024-04-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0008_recipe_blog_recipe_slider_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_blog',
            name='pic',
            field=models.FileField(default=0, upload_to='recipe_slider_img'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='recipe_slider',
        ),
    ]
