# Generated by Django 5.0.3 on 2024-04-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0009_recipe_blog_pic_delete_recipe_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_blog',
            name='Ingredients',
        ),
    ]
