# Generated by Django 5.0.3 on 2024-04-18 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0012_receipepost_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipeimage',
            name='receipe_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='delicious.receipepost'),
        ),
    ]
