# Generated by Django 5.0.3 on 2024-04-18 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0013_alter_receipeimage_receipe_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipeimage',
            name='receipe_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipe_post_set', to='delicious.receipepost'),
        ),
    ]
