# Generated by Django 5.0.3 on 2024-04-18 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0014_alter_receipeimage_receipe_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_set_ingd', to='delicious.receipepost'),
        ),
        migrations.AlterField(
            model_name='recipecontentsection',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_set', to='delicious.receipepost'),
        ),
    ]
