# Generated by Django 5.0.3 on 2024-04-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0015_alter_ingredient_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
    ]
