# Generated by Django 5.0.3 on 2024-04-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0016_remove_ingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipepost',
            name='lavel',
            field=models.CharField(choices=[('Begineer', 'Begineer'), ('Intermedate', 'Intermedate'), ('Expert', 'Expert')], default='Begineer', max_length=50),
        ),
    ]
