# Generated by Django 5.0.3 on 2024-04-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0018_feedback_remove_receipepost_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipepost',
            name='featured_item',
            field=models.BooleanField(default=False),
        ),
    ]
